/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Miscellaneous; 

import Articles.ArtList;
import Customers.CustList;
import Sales.SalesList;
import Services.ServList;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author egimenez
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbArt = new javax.swing.JButton();
        jbServ = new javax.swing.JButton();
        jbCust = new javax.swing.JButton();
        jbSales = new javax.swing.JButton();
        jlPpal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbArt.setText("Artículos");
        jbArt.setToolTipText("Artículos");
        jbArt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        jbArt.setContentAreaFilled(false);
        jbArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbArtActionPerformed(evt);
            }
        });

        jbServ.setText("Servicios");
        jbServ.setToolTipText("Servicios");
        jbServ.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        jbServ.setContentAreaFilled(false);
        jbServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbServActionPerformed(evt);
            }
        });

        jbCust.setText("Clientes");
        jbCust.setToolTipText("Clientes");
        jbCust.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        jbCust.setContentAreaFilled(false);
        jbCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCustActionPerformed(evt);
            }
        });

        jbSales.setText("Servicios/Ventas");
        jbSales.setToolTipText("Servicios/Ventas");
        jbSales.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        jbSales.setContentAreaFilled(false);
        jbSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalesActionPerformed(evt);
            }
        });

        jlPpal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPpal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/estetica_facial_3.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jbCust, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jbServ, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jbArt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jbSales, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jlPpal, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jbCust, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jbServ, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jbArt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jbSales, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jlPpal, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jbArt.getAccessibleContext().setAccessibleDescription("");
        jbServ.getAccessibleContext().setAccessibleDescription("");
        jbCust.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* Evento que se dispara cuando se acciona el
     * pulsador de artículos */
    private void jbArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbArtActionPerformed

        // Definiciones locales
        ArtList al;

        // Lanzar el JDialog con la lista de artículos
        al = new ArtList(this, true, false);
        al.setTitle("Lista Artículos");
        al.pack();
        al.setVisible(true);
    }//GEN-LAST:event_jbArtActionPerformed

    /* Evento que se dispara cuando se acciona el
     * pulsador de clientes */
    private void jbCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCustActionPerformed

        // Definiciones locales
        CustList cl;

        // Lanzar el JDialog con la lista de clientes
        cl = new CustList(this, true, false);
        cl.setTitle("Lista Clientes");
        cl.pack();
        cl.setVisible(true);
    }//GEN-LAST:event_jbCustActionPerformed

    /* Evento que se dispara cuando se acciona el
     * pulsador de servicios/ventas */
    private void jbSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalesActionPerformed

        // Definiciones locales
        SalesList sl;

        // Lanzar el JDialog con la lista de servicios/ventas
        sl = new SalesList(this, true);
        sl.setTitle("Lista Servicios/Ventas");
        sl.pack();
        sl.setVisible(true);
    }//GEN-LAST:event_jbSalesActionPerformed

    /* Evento que se dispara cuando se acciona el
     * pulsador de servicios */
    private void jbServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbServActionPerformed

        // Definiciones locales
        ServList sl;

        // Lanzar el JDialog con la lista de servicios
        sl = new ServList(this, true, false);
        sl.setTitle("Lista Servicios");
        sl.pack();
        sl.setVisible(true);
    }//GEN-LAST:event_jbServActionPerformed

    /* Cambiar icono Java por uno propio */
    private void init() {
        try {
            this.setIconImage(ImageIO.read(new File("./src/Images/estetica_facial_3.jpg")));
        } catch (IOException e) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbArt;
    private javax.swing.JButton jbCust;
    private javax.swing.JButton jbSales;
    private javax.swing.JButton jbServ;
    private javax.swing.JLabel jlPpal;
    // End of variables declaration//GEN-END:variables
}
